version: '3'

services:
  web:
    container_name: chatgpt-web
    image: registry.cn-beijing.aliyuncs.com/jingbingshuai/chatgpt-web:latest
    environment:
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

